# ----------- CONFIGURABLE START -----------
title:            "Jeong-Yoon"
description:      "-"
url:              "https://Jeong-Yoon.github.io" # Site url, without a slash at the end. # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl:          "https://Jeong-Yoon.github.io"
signoff:          "Jeong-Yoon" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About me
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"

# # The font used for headings. Expects a string that is a valid CSS font-family value.
# font_heading:        "'Noto Sans', 'Nanum Gothic', Helvetica, Arial, sans-serif"

# # The text font. Expects a string that is a valid CSS font-family value.
# font:                "'Noto Sans','Nanum Gothic', Helvetica, Arial, sans-serif"

# # The string encoding what fonts to fetch from Google Fonts.
# # See: https://qwtel.com/hydejack/docs/configuration/
# google_fonts:        Noto+Sans:400,400i,700,700i

# If you do not use a Google Fonts, uncomment the line below
# no_google_fonts:     true

sass:
  sass_dir: stylesheets
  style: compressed

# Site Author
author:
 name             : "Jeong Yoon"
 avatar           : "/assets/images/bio-photo.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg" 사진도 추가해 봅니다.
